const coffeeMenu = [
    // Laptop Coffee Category
    {
        id: 1,
        image: "images/coffee/c1.jpg",
        title: "Espresso Laptop Brew",
        description: "A bold and rich espresso, crafted for intense focus.",
        price: 3.99,
        category: "Laptop Coffee",
        rating: 4.5,
    },
    {
        id: 2,
        image: "images/coffee/c2.jpg",
        title: "Cappuccino Code Boost",
        description: "A smooth cappuccino perfect for powering through work.",
        price: 4.49,
        category: "Laptop Coffee",
        rating: 4.7,
    },
    {
        id: 3,
        image: "images/coffee/c3.jpg",
        title: "Latte Logic",
        description: "A creamy latte designed to inspire your next big idea.",
        price: 4.99,
        category: "Laptop Coffee",
        rating: 4.8,
    },
    {
        id: 4,
         image: "images/coffee/c4.jpg",
        title: "Mocha Mastermind",
        description: "A chocolatey mocha, perfect for late-night creativity.",
        price: 5.49,
        category: "Laptop Coffee",
        rating: 4.6,
    },

    // Traditional Coffee Category
    {
        id: 5,
        image: "images/coffee/c5.jpg",
        title: "Classic Americano",
        description: "A simple, yet elegant black coffee for a classic taste.",
        price: 2.99,
        category: "Traditional Coffee",
        rating: 4.3,
    },
    {
        id: 6,
        image: "images/coffee/c6.jpg",
        title: "Traditional Espresso",
        description: "An authentic espresso shot with intense flavor.",
        price: 2.49,
        category: "Traditional Coffee",
        rating: 4.7,
    },
    {
        id: 7,
        image: "images/coffee/c7.jpg",
        title: "Classic Cappuccino",
        description: "A balanced blend of espresso, steamed milk, and foam.",
        price: 3.99,
        category: "Traditional Coffee",
        rating: 4.6,
    },
    {
        id: 8,
        image: "images/coffee/c8.webp",
        title: "Traditional Flat White",
        description: "A rich and smooth coffee with a velvety finish.",
        price: 4.29,
        category: "Traditional Coffee",
        rating: 4.8,
    },

    // Special Coffee Category
    {
        id: 9,
        image: "images/coffee/c9.jpg",
        title: "Caramel Macchiato",
        description: "A delicious mix of espresso, milk, and caramel syrup.",
        price: 5.29,
        category: "Special Coffee",
        rating: 4.9,
    },
    {
        id: 10,
        image: "images/coffee/c10.jpg",
        title: "Vanilla Latte Bliss",
        description: "A vanilla-infused latte for a touch of sweetness.",
        price: 5.19,
        category: "Special Coffee",
        rating: 4.7,
    },
    {
        id: 11,
        image: "images/coffee/c11.webp",
        title: "Hazelnut Mocha",
        description: "A nutty and chocolatey coffee experience.",
        price: 5.49,
        category: "Special Coffee",
        rating: 4.8,
    },
    {
        id: 12,
        image: "images/coffee/c12.jpg",
        title: "Pumpkin Spice Latte",
        description: "A seasonal favorite with notes of pumpkin and cinnamon.",
        price: 5.99,
        category: "Special Coffee",
        rating: 4.9,
    },

    // More Laptop Coffee
    {
        id: 13,
        image: "images/coffee/c13.webp",
        title: "Startup Espresso",
        description: "A perfect energy booster for your entrepreneurial spirit.",
        price: 3.89,
        category: "Laptop Coffee",
        rating: 4.5,
    },

    // More Traditional Coffee
    {
        id: 14,
        image: "images/coffee/c14.webp",
        title: "Classic Black",
        description: "A strong black coffee to awaken your senses.",
        price: 2.79,
        category: "Traditional Coffee",
        rating: 4.4,
    },

    // More Special Coffee
    {
        id: 15,
        image: "images/coffee/c15.jpg",
        title: "Peppermint Mocha",
        description: "A refreshing blend of peppermint and chocolate.",
        price: 5.59,
        category: "Special Coffee",
        rating: 4.9,
    },
    {
        id: 16,
        image: "images/coffee/c16.jpg",
        title: "Iced Caramel Latte",
        description: "An iced latte with caramel, perfect for hot days.",
        price: 4.99,
        category: "Special Coffee",
        rating: 4.8,
    },
    {
        id: 17,
        image: "images/coffee/c17.jpg",
        title: "Coconut Cold Brew",
        description: "A refreshing cold brew with a hint of coconut.",
        price: 5.29,
        category: "Special Coffee",
        rating: 4.7,
    },

    {
        id: 18,
        image: "images/coffee/c18.jpg",
        title: "Midnight Latte",
        description: "A soothing latte to keep your night productive.",
        price: 4.59,
        category: "Laptop Coffee",
        rating: 4.6,
    },
    {
        id: 19,
        image: "images/coffee/c19.jpg",
        title: "Bold Espresso",
        description: "A dark and bold espresso for coffee lovers.",
        price: 2.99,
        category: "Traditional Coffee",
        rating: 4.5,
    },
    {
        id: 20,
        image: "images/coffee/c20.webp",
        title: "Toffee Nut Latte",
        description: "A delightful blend of espresso, milk, and toffee nut flavor.",
        price: 5.49,
        category: "Special Coffee",
        rating: 4.9,
    },
];

export default coffeeMenu;
